### ISSUE TITLE
Benchmarking results differ but should give same results

### ISSUE THREAD

**Issue by Ben1980** [FredTingaud/quick-bench-front-end#27]
I have a example [Gist](https://gist.github.com/Ben1980/405495a5b8c101830cfb6280d41b7959) which is comparing the performance of data access of a couple of containers.

If you run all 5 benchmarks you get the following result pointing out that std::vector<T> is clearly slower than an array.
![fRbo3teGacF4mogrNWtecLZskko](https://user-images.githubusercontent.com/919260/68684988-aff51180-0569-11ea-9f6b-0eabeae4e222.png)

If you run just the `OneDimVector` and `OneDimRawArray` benchmarks std::vector has the same performance as a raw C array.
![Y02VV_qGzuvHLyUXuxqBwX8VUc0](https://user-images.githubusercontent.com/919260/68685186-082c1380-056a-11ea-9d6b-75bb5c938059.png)

Is this a possible bug? Or is it because GCC-9.1 (both cases with -O3) can't really optimizing the 5 benchmarks case?

**Comment by FredTingaud** [comment]
Looking at the assembly code, the mathematical operation done in both cases is not the same:
mulsd  (%rax),%xmm0
add    $0xfa0,%rax
add    $0x8,%rdx
addsd  %xmm0,%xmm1
movsd  %xmm1,(%rcx)

vs

movupd (%rax),%xmm2
add    $0xfa0,%rax
add    $0x8,%rdx
unpcklpd %xmm0,%xmm0
mulpd  %xmm2,%xmm0
addpd  %xmm0,%xmm1

Note that you are doing += on memory that you didn't initialize first in the case of the pointers.

Also the for(auto _ : state) can be run a different number of time for each benchmark.

From what I see, it is indeed surprising but due to how the benchmark is written and how gcc (and clang) optimize it.

**Comment by Ben1980** [comment]
Ok thanks, I adjusted the code by initializing the raw array. But results are still same at the end as reported above. As far as i can see they do the same now, Am I interpreting this correct?
OneDimVec:
0.26%  movupd (%rax),%xmm2
13.79% add    $0xfa0,%rax
25.09% add    $0x8,%rdx
       unpcklpd %xmm0,%xmm0
0.26%  mulpd  %xmm2,%xmm0
5.71%  addpd  %xmm0,%xmm1
52.65% cmp    %rcx,%rax

RawArray:
0.38%  movupd (%rax),%xmm2
16.29% add    $0xfa0,%rax
22.77% add    $0x8,%rdx
       unpcklpd %xmm0,%xmm0
0.32%  mulpd  %xmm2,%xmm0
6.93%  addpd  %xmm0,%xmm1
50.55% cmp    %rcx,%rax

> Also the for(auto _ : state) can be run a different number of time for each benchmark.

But shouldn't this make any difference because you show the mean result i guess?
